import type { Metadata } from "next";
import { Roboto, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ButtonUp from "@/components/ButtonUp";

const roboto = Roboto({
  variable: "--font-roboto",
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: {
    default: 'Йога-студія Vinyasa - Віньяса-йога, заняття для початківців',
    template: '%s | Йога-студія Vinyasa - Віньяса-йога, заняття для початківців'
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${roboto.variable} ${montserrat.variable} h-ful antialiased`}>
      <body className="min-h-screen flex flex-col">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
      <ButtonUp />
    </html>
  );
}
